# Generated by Django 5.0.7 on 2024-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20),
        ),
    ]
