# Generated by Django 5.0.7 on 2024-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To Do'), ('In progress', 'In Progress'), ('Done', 'Done')], max_length=20),
        ),
    ]
